apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
  creationTimestamp: "2026-03-03T03:55:54Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.14.3
    helm.sh/chart: ingress-nginx-4.14.3
  name: ingress-nginx-controller
  namespace: ingress-nginx
  resourceVersion: "497516"
  uid: 878ed5ca-f7d5-46fd-aed5-daa7ebd775da
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.234.91
  clusterIPs:
  - 10.0.234.91
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 31232
    port: 8080
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 31353
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.84.230.209
      ipMode: VIP
